apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-deploy
spec:
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
      - name: conversao
        image: gustavolfee/conversao-temperatura:1.0

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-service
spec:
  selector:
    app: conversao
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  type: NodePort

